name: Delete Merged Branches

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["delete-branch"]

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete merged branches
        uses: actions/github-script@v4
        with:
          script: |
            const { data: pullRequests } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              per_page: 100
            });
            console.log('All Pull Requests:', pullRequests.map(pr => pr.head.ref));
            const mergedBranches = pullRequests
              .filter(pr => pr.merged_at)
              .map(pr => pr.head.ref);
            console.log('Merged Branches:', mergedBranches);

            const { data: branches } = await github.repos.listBranches({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const thirtyDaysAgo = new Date();
            thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

            const branchesToDelete = branches.filter(branch => {
              const branchCommit = branch.commit.committer.date;
              return mergedBranches.includes(branch.name) && new Date(branchCommit) < thirtyDaysAgo;
            });

            console.log('Branches to Delete:', branchesToDelete);



            for (const branch of branchesToDelete) {
              await github.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branch.name}`
              });
            }

